import type { FastifyRequest, FastifyReply } from 'fastify'

/**
 * RFC 9457 Problem Details standard fields
 */
export interface ProblemDetails {
  /**
   * URI reference that identifies the problem type.
   * When dereferenced, should provide human-readable documentation.
   * @default "about:blank"
   */
  type?: string

  /**
   * Short, human-readable summary of the problem type.
   * SHOULD NOT change between occurrences of the same type.
   */
  title?: string

  /**
   * HTTP status code generated by the origin server.
   */
  status?: number

  /**
   * Human-readable explanation specific to this occurrence.
   * SHOULD be different for each occurrence.
   */
  detail?: string

  /**
   * URI reference that identifies the specific occurrence.
   * May or may not provide additional information when dereferenced.
   */
  instance?: string

  /**
   * Custom extension fields (any additional properties)
   */
  [key: string]: unknown
}

/**
 * Options for creating a ProblemDocument
 */
export interface ProblemOptions extends Omit<ProblemDetails, 'status'> {
  /**
   * Original cause of the error (for logging/debug)
   */
  cause?: Error
}

/**
 * Global plugin options
 */
export interface FastifyProblemDetailsOptions {
  /**
   * Base URL for error types.
   * Types will be constructed as: `${baseUrl}/${errorType}`
   * @example "https://api.example.com/errors"
   */
  baseUrl?: string

  /**
   * Include stack trace in response (development only)
   * @default false in production, true otherwise
   */
  includeStackTrace?: boolean

  /**
   * Default language for error titles
   * @default "en"
   */
  defaultLanguage?: 'en' | 'it' | 'es' | 'de' | 'fr'

  /**
   * Custom map of status codes to titles
   * @example { 404: "Risorsa non trovata" }
   */
  titleMap?: Record<number, string>

  /**
   * Custom map of status codes to type URI slugs
   * @example { 404: "not-found", 403: "forbidden" }
   */
  typeMap?: Record<number, string>

  /**
   * Hook called before sending the problem response
   * Useful for logging, monitoring, etc.
   */
  onProblem?: (problem: ProblemDetails, request: FastifyRequest) => void | Promise<void>

  /**
   * Support Accept: application/problem+xml
   * @default false
   */
  supportXml?: boolean

  /**
   * Convert all Fastify errors to Problem Details
   * @default true
   */
  convertFastifyErrors?: boolean

  /**
   * Hide internal details in production
   * @default true
   */
  sanitizeProduction?: boolean
}

/**
 * Predefined HTTP error methods available on reply
 */
export interface ProblemReplies {
  // 4xx Client Errors
  badRequest(options?: ProblemOptions): FastifyReply
  unauthorized(options?: ProblemOptions): FastifyReply
  paymentRequired(options?: ProblemOptions): FastifyReply
  forbidden(options?: ProblemOptions): FastifyReply
  notFound(options?: ProblemOptions): FastifyReply
  methodNotAllowed(options?: ProblemOptions): FastifyReply
  notAcceptable(options?: ProblemOptions): FastifyReply
  conflict(options?: ProblemOptions): FastifyReply
  gone(options?: ProblemOptions): FastifyReply
  unprocessableEntity(options?: ProblemOptions): FastifyReply
  tooManyRequests(options?: ProblemOptions): FastifyReply

  // 5xx Server Errors
  internalServerError(options?: ProblemOptions): FastifyReply
  notImplemented(options?: ProblemOptions): FastifyReply
  badGateway(options?: ProblemOptions): FastifyReply
  serviceUnavailable(options?: ProblemOptions): FastifyReply
  gatewayTimeout(options?: ProblemOptions): FastifyReply
}

/**
 * Custom problem type configuration
 */
export interface ProblemTypeConfig {
  status: number
  title: string
  type?: string
}

/**
 * Fastify module augmentation
 */
declare module 'fastify' {
  interface FastifyReply extends ProblemReplies {
    /**
     * Send a custom Problem Details response
     */
    problem(statusCode: number, options?: ProblemOptions): FastifyReply

    /**
     * Create a ProblemDocument without sending it
     */
    createProblem(statusCode: number, options?: ProblemOptions): ProblemDetails
  }

  interface FastifyInstance {
    /**
     * Register a custom problem type
     */
    registerProblemType(name: string, config: ProblemTypeConfig): void

    /**
     * Map of registered problem types
     */
    problemTypes: Map<string, { status: number; title: string; type: string }>
  }
}
